import type { CityOption } from './types'

export const cities: CityOption[] = [
  { code: 'PEK', name: '北京', airports: ['首都机场', '大兴机场'] },
  { code: 'SHA', name: '上海', airports: ['虹桥机场', '浦东机场'] },
  { code: 'CAN', name: '广州', airports: ['白云机场'] },
  { code: 'CTU', name: '成都', airports: ['天府机场', '双流机场'] },
  { code: 'SZX', name: '深圳', airports: ['宝安机场'] },
  { code: 'HGH', name: '杭州', airports: ['萧山机场'] },
  { code: 'CKG', name: '重庆', airports: ['江北机场'] },
  { code: 'WUH', name: '武汉', airports: ['天河机场'] },
  { code: 'XIY', name: '西安', airports: ['咸阳机场'] },
  { code: 'KMG', name: '昆明', airports: ['长水机场'] },
  { code: 'NKG', name: '南京', airports: ['禄口机场'] },
  { code: 'CSX', name: '长沙', airports: ['黄花机场'] },
  { code: 'TSN', name: '天津', airports: ['滨海机场'] },
  { code: 'FOC', name: '福州', airports: ['长乐机场'] },
  { code: 'XMN', name: '厦门', airports: ['高崎机场'] },
  { code: 'DLC', name: '大连', airports: ['周水子机场'] },
  { code: 'HRB', name: '哈尔滨', airports: ['太平机场'] },
  { code: 'SYX', name: '三亚', airports: ['凤凰机场'] },
  { code: 'KWL', name: '桂林', airports: ['两江机场'] },
  { code: 'URC', name: '乌鲁木齐', airports: ['地窝堡机场'] },
  { code: 'TAO', name: '青岛', airports: ['胶东机场'] },
  { code: 'TNA', name: '济南', airports: ['遥墙机场'] },
  { code: 'SHE', name: '沈阳', airports: ['桃仙机场'] },
  { code: 'HAK', name: '海口', airports: ['美兰机场'] },
  { code: 'NNG', name: '南宁', airports: ['吴圩机场'] },
  { code: 'CGO', name: '郑州', airports: ['新郑机场'] },
  { code: 'TYN', name: '太原', airports: ['武宿机场'] },
  { code: 'HET', name: '呼和浩特', airports: ['白塔机场'] },
  { code: 'LHW', name: '兰州', airports: ['中川机场'] },
  { code: 'XNN', name: '西宁', airports: ['曹家堡机场'] },
  { code: 'INC', name: '银川', airports: ['河东机场'] },
  { code: 'NGB', name: '宁波', airports: ['栎社机场'] },
  { code: 'WNZ', name: '温州', airports: ['龙湾机场'] },
  { code: 'ZUH', name: '珠海', airports: ['金湾机场'] },
  { code: 'SWA', name: '揭阳', airports: ['潮汕机场'] },
  { code: 'WUX', name: '无锡', airports: ['硕放机场'] },
]
